### ISSUE TITLE
Homeschool Tracker

### ISSUE THREAD

**Issue by mblayman** [mblayman/homeschool#205]
* [ ] Read docs and use service
* [ ] Write up notes on experience
* [ ] Write comparison documentation
* [ ] Share experience with WTM
