### ISSUE TITLE
Teacher checklist

### ISSUE THREAD

**Issue by mblayman** [mblayman/homeschool#610]
A customer requested the ability to have a teacher checklist for the week.

* [x] add checklist option to week view
* [x] add ability to remove courses from checklist
* [x] user documentation
* [x] announcement blog post
* [x] announcement notification
